apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: sonarqube
    meta.helm.sh/release-namespace: sonarqube
  creationTimestamp: "2022-08-20T17:42:12Z"
  labels:
    app.kubernetes.io/instance: sonarqube
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.15.0
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: sonarqube-postgresql-headless
  namespace: sonarqube
  resourceVersion: "11160"
  uid: 63b3a6c7-3884-4c8c-8019-acc6aac2e261
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: sonarqube
    app.kubernetes.io/name: postgresql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
