---
- name: Add Docker GPG apt Key
  apt_key:
    url: "{{ APT_KEY_URL }}"
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "{{ APT_REPO_URL }}"
    state: present

- name: Install Docker-CE
  apt:
    name: docker-ce
    state: latest
    update_cache: True
  notify: docker-successs

